# Форматы чатов (можно создавать свои). Поддерживается PlaceholderAPI
# Плейсы плагина:
# %player% - ник игрока
# %prefix% - префикс игрока (берется из vault api)
# %suffix% - суффикс игрока (берется из vault api)
# %dph% - плейсхолдер группы
# %message% - сообщение игрока
chatFormats:
  local:
    format: "&aⓁ&f %prefix% &8⋆&f %player%&7:%dph% %message%"
    radius: 100
    # Если префикс указан пустым - канал становится дефолтным
    prefix: ''
    # Кулдаун для чата в милисекундах
    cooldown: 500
    # Право на канал, чтобы в него писать и видеть
    # Если канал дефолтный - право на него не нужно. Если не указано - используется формат pchat.channel.имя_из_конфига
    permission: pchat.channel.local
  global:
    format: "&cⒼ&f %prefix% &8⋆&f %player%&7:%dph% %message%"
    # Будет виден всем игрокам если указано -1
    radius: -1
    # В случае, если будет указан дубликат префикса - к префиксу будет присуждён последний канал из конфига с таким префиксом
    prefix: '!'
    cooldown: 1500
  # Сообщение о кулдауне (может быть отдельно применено к каналу)
  cooldownMessage: "&e[♻]&f Вы слишком быстро пишите! Подождите еще %time%"
  # Ховер текст (может быть отдельно применён к каналу)
  # При включении заменяет логику работы чата, что может сказаться на работе других плагинов, включающих в себя его форматирование.
  # Сообщения будут отправляться игрокам от сервера.
  hoverText:
    enable: false
    format: |-
      &fИнформация об игроке %player%
      &fРанг: &6%vault_group%
      &fХП: &6%player_health%
      &fОпыт: &6%player_exp%
    # Настройка клик ивента (действие при клике на сообщение игрока)
    clickEvent:
      enable: false
      actionType: SUGGEST_COMMAND
      actionValue: "/msg %player%"
  # Плейсхолделы для донатов по группам (может быть применён отдельно к каналу)
  donatePlaceholders:
    default: "&7"
    admin: "&f&l"
  # Приоритет слушателя чата (https://jd.papermc.io/paper/1.21.11/org/bukkit/event/EventPriority.html)
  chatPriority: LOW
  # Пересылать ли чаты между серверами в одной сети (Пока доступно только для глобальных чатов)
  proxy: false

# Настройка блокировки чата для новичков
newbieChat:
  # Включен ли newbieChat
  enable: true
  # Кулдаун на чат для новичков в секундах
  newbieCooldown: 600
  # Сообщение для чата для новичков
  newbieChatMessage: "&c[★] &6Подожди! Что-бы написать в чат вы должны отыграть 10 минут на сервере, осталось &c%time%"
  # Сообщение для команд для новичков
  newbieCommandMessage: "&c[★] &6Подожди! Что-бы написать данную команды вы должны отыграть 10 минут на сервере, осталось &c%time%"
  # Команды, которые будут попадать под newbieChat
  newbieCommands:
    - "/m"
    - "/pm"
    - "/msg"
    - "/t"
    - "/tell"
    - "/w"
    - "/whisper"

# Настройка автосообщений
autoMessage:
  # Включел ли autoMessage
  enable: true
  # Выдавать ли их рандомно
  random: true
  # Промежуток между сообщениями в секундах
  messageInterval: 300
  # Сообщения
  # Можно указывать айди какое хотите
  # Доступен ховертекст и клик-ивент. Указывать через hoverText={Текст-при-наведении} и clickEvent={айди-действия;действие-при-клике}
  # Доступные действия для clickEvent: https://hub.spigotmc.org/jenkins/job/BungeeCord/ws/chat/target/apidocs/net/md_5/bungee/api/chat/ClickEvent.Action.html (run_command работает хер знает как, вините md_5)
  # Также доступны кнопки. Создаются при помощи button={Текст-кнопки;Действие1;Действие2}. Действия 1 и 2 - hoverText и clickEvent соответственно.
  messages:
    1:
      - "[PromisedChat] &aпервое авто-сообщение"
    2:
      - "[PromisedChat] &bвторое авто-сообщение линия 1"
      - "[PromisedChat] &bвторое авто-сообщение линия 2"
    3:
      - "[PromisedChat] &cтретье авто-сообщение с ховертекстом hoverText={Тот самый текст}"
      - "[PromisedChat] &cтретье авто-сообщение с клик ивентом clickEvent={SUGGEST_COMMAND;/say Я нажал на автосообщение в чате!}"

# Плейсхолдеры плагина
placeholders:
  time:
    hours: ' ч. '
    minutes: ' мин. '
    seconds: ' сек. '